typography_spectrum: 0.028423352632671595
color:
  brandStrength: 0.475772459525615
  lightness: 0.12365814158692956
  saturation: 0.6706855446100235
  rhythmicContrast: 0.4812173193786293
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
layout_spectrum: 0.08079709974117577
author:
  name: Rafa
  email: rafaaraos@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/101cfa76-4bac-49e6-8572-93742c5f0e86.png
name: GeRM Group
navigation:
  - name: Who we are
    id: 8cb49e98-403a-4375-8a26-843bb3515abb
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d8b5dee7-f299-4e50-a6f5-a3c986c10a26.png
title: Genomic and Resistant Microbes
description: GeRM Group
